version: "3"

volumes:
  pgdata:

services:
  app:
    build: .
    container_name: app
    restart: always
    expose:
      - 80
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    networks:
      shared_network:
        ipv4_address: 10.5.0.11

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    expose:
      - 5432
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      shared_network:
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    logging:
      driver: none
    networks:
      shared_network:
    
networks:
  shared_network:
    external: true
